[package]
name = "ZKIntentBook"
edition = "2024.beta"
version = "0.1.0"
authors = ["ZK-IntentBook Team"]
published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }
DeepBookV3 = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "main" }

[addresses]
zk_intentbook = "0x0"
sui = "0x2"
deepbook = "0xdee9"
